export const CM_THEME_ATTR = "data-cm-theme";

/** CSS custom properties applied on #vditor when a CodeMirror color theme is selected. */
export type CMThemeVars = Record<string, string>;

export const CM_THEME_VAR_KEYS: string[] = [
    "--cm-bg-color",
    "--cm-fg-color",
    "--cm-active-line-bg",
    "--cm-cursor-fg",
    "--cm-line-number-fg",
    "--cm-line-number-active-fg",
    "--cm-selection-bg-inactive",
    "--cm-selection-bg-focused",
    "--cm-selection-highlight-bg",
    "--cm-bracket-match-bg",
    "--cm-bracket-match-border",
    "--cm-syntax-comment",
    "--cm-syntax-keyword",
    "--cm-syntax-string",
    "--cm-syntax-number",
    "--cm-syntax-atom",
    "--cm-syntax-property",
    "--cm-syntax-attribute",
    "--cm-syntax-variable",
    "--cm-syntax-def",
    "--cm-syntax-bracket",
    "--cm-syntax-tag",
    "--cm-syntax-link",
    "--cm-syntax-error",
];

/** null = follow editor / VS Code theme (default). */
export interface ICodeMirrorThemeGroup {
    titleKey: string;
    themes: string[];
}

export const CM_THEME_GROUPS: ICodeMirrorThemeGroup[] = [
    {
        titleKey: "code-theme-section-system",
        themes: ["default"],
    },
    {
        titleKey: "code-theme-section-light",
        themes: ["github", "solarized-light", "material-light", "quiet-light", "one-light"],
    },
    {
        titleKey: "code-theme-section-dark",
        themes: ["dracula", "monokai", "one-dark", "solarized-dark", "material-dark"],
    },
];

export const CM_THEME_IDS: string[] = CM_THEME_GROUPS.flatMap((group) => group.themes);

export const CM_COLOR_THEMES: Record<string, CMThemeVars | null> = {
    default: null,
    github: {
        "--cm-bg-color": "#f6f8fa",
        "--cm-fg-color": "#24292f",
        "--cm-active-line-bg": "rgba(0, 0, 0, 0.04)",
        "--cm-cursor-fg": "#24292f",
        "--cm-line-number-fg": "#656d76",
        "--cm-line-number-active-fg": "#24292f",
        "--cm-selection-bg-inactive": "rgba(84, 174, 255, 0.25)",
        "--cm-selection-bg-focused": "rgba(84, 174, 255, 0.35)",
        "--cm-selection-highlight-bg": "rgba(84, 174, 255, 0.15)",
        "--cm-bracket-match-bg": "rgba(84, 174, 255, 0.2)",
        "--cm-bracket-match-border": "#54aeff",
        "--cm-syntax-comment": "#6a737d",
        "--cm-syntax-keyword": "#cf222e",
        "--cm-syntax-string": "#0a3069",
        "--cm-syntax-number": "#0550ae",
        "--cm-syntax-atom": "#0550ae",
        "--cm-syntax-property": "#953800",
        "--cm-syntax-attribute": "#116329",
        "--cm-syntax-variable": "#24292f",
        "--cm-syntax-def": "#8250df",
        "--cm-syntax-bracket": "#24292f",
        "--cm-syntax-tag": "#116329",
        "--cm-syntax-link": "#0969da",
        "--cm-syntax-error": "#cf222e",
    },
    "solarized-light": {
        "--cm-bg-color": "#fdf6e3",
        "--cm-fg-color": "#657b83",
        "--cm-active-line-bg": "rgba(0, 0, 0, 0.05)",
        "--cm-cursor-fg": "#657b83",
        "--cm-line-number-fg": "#93a1a1",
        "--cm-line-number-active-fg": "#657b83",
        "--cm-selection-bg-inactive": "rgba(181, 137, 0, 0.2)",
        "--cm-selection-bg-focused": "rgba(181, 137, 0, 0.35)",
        "--cm-selection-highlight-bg": "rgba(181, 137, 0, 0.12)",
        "--cm-bracket-match-bg": "rgba(181, 137, 0, 0.2)",
        "--cm-bracket-match-border": "#b58900",
        "--cm-syntax-comment": "#93a1a1",
        "--cm-syntax-keyword": "#859900",
        "--cm-syntax-string": "#2aa198",
        "--cm-syntax-number": "#d33682",
        "--cm-syntax-atom": "#cb4b16",
        "--cm-syntax-property": "#268bd2",
        "--cm-syntax-attribute": "#b58900",
        "--cm-syntax-variable": "#657b83",
        "--cm-syntax-def": "#268bd2",
        "--cm-syntax-bracket": "#657b83",
        "--cm-syntax-tag": "#268bd2",
        "--cm-syntax-link": "#268bd2",
        "--cm-syntax-error": "#dc322f",
    },
    "material-light": {
        "--cm-bg-color": "#fafafa",
        "--cm-fg-color": "#546e7a",
        "--cm-active-line-bg": "rgba(0, 0, 0, 0.04)",
        "--cm-cursor-fg": "#546e7a",
        "--cm-line-number-fg": "#90a4ae",
        "--cm-line-number-active-fg": "#546e7a",
        "--cm-selection-bg-inactive": "rgba(128, 203, 196, 0.3)",
        "--cm-selection-bg-focused": "rgba(128, 203, 196, 0.45)",
        "--cm-selection-highlight-bg": "rgba(128, 203, 196, 0.15)",
        "--cm-bracket-match-bg": "rgba(128, 203, 196, 0.25)",
        "--cm-bracket-match-border": "#80cbc4",
        "--cm-syntax-comment": "#90a4ae",
        "--cm-syntax-keyword": "#7c4dff",
        "--cm-syntax-string": "#39adb5",
        "--cm-syntax-number": "#f76d47",
        "--cm-syntax-atom": "#f76d47",
        "--cm-syntax-property": "#9c27b0",
        "--cm-syntax-attribute": "#ff5370",
        "--cm-syntax-variable": "#546e7a",
        "--cm-syntax-def": "#6182b8",
        "--cm-syntax-bracket": "#546e7a",
        "--cm-syntax-tag": "#e53935",
        "--cm-syntax-link": "#6182b8",
        "--cm-syntax-error": "#ff5370",
    },
    "quiet-light": {
        "--cm-bg-color": "#f5f5f5",
        "--cm-fg-color": "#333333",
        "--cm-active-line-bg": "rgba(0, 0, 0, 0.04)",
        "--cm-cursor-fg": "#333333",
        "--cm-line-number-fg": "#999999",
        "--cm-line-number-active-fg": "#333333",
        "--cm-selection-bg-inactive": "rgba(163, 184, 204, 0.4)",
        "--cm-selection-bg-focused": "rgba(163, 184, 204, 0.55)",
        "--cm-selection-highlight-bg": "rgba(163, 184, 204, 0.2)",
        "--cm-bracket-match-bg": "rgba(163, 184, 204, 0.35)",
        "--cm-bracket-match-border": "#a3b8cc",
        "--cm-syntax-comment": "#777777",
        "--cm-syntax-keyword": "#004276",
        "--cm-syntax-string": "#bc670f",
        "--cm-syntax-number": "#004276",
        "--cm-syntax-atom": "#004276",
        "--cm-syntax-property": "#004276",
        "--cm-syntax-attribute": "#006699",
        "--cm-syntax-variable": "#333333",
        "--cm-syntax-def": "#006699",
        "--cm-syntax-bracket": "#333333",
        "--cm-syntax-tag": "#004276",
        "--cm-syntax-link": "#006699",
        "--cm-syntax-error": "#cc0000",
    },
    "one-light": {
        "--cm-bg-color": "#fafafa",
        "--cm-fg-color": "#383a42",
        "--cm-active-line-bg": "rgba(0, 0, 0, 0.04)",
        "--cm-cursor-fg": "#526fff",
        "--cm-line-number-fg": "#9d9d9f",
        "--cm-line-number-active-fg": "#383a42",
        "--cm-selection-bg-inactive": "rgba(184, 184, 184, 0.35)",
        "--cm-selection-bg-focused": "rgba(184, 184, 184, 0.5)",
        "--cm-selection-highlight-bg": "rgba(184, 184, 184, 0.2)",
        "--cm-bracket-match-bg": "rgba(184, 184, 184, 0.25)",
        "--cm-bracket-match-border": "#526fff",
        "--cm-syntax-comment": "#a0a1a7",
        "--cm-syntax-keyword": "#a626a4",
        "--cm-syntax-string": "#50a14f",
        "--cm-syntax-number": "#986801",
        "--cm-syntax-atom": "#986801",
        "--cm-syntax-property": "#e45649",
        "--cm-syntax-attribute": "#986801",
        "--cm-syntax-variable": "#e45649",
        "--cm-syntax-def": "#4078f2",
        "--cm-syntax-bracket": "#383a42",
        "--cm-syntax-tag": "#e45649",
        "--cm-syntax-link": "#4078f2",
        "--cm-syntax-error": "#e45649",
    },
    dracula: {
        "--cm-bg-color": "#282a36",
        "--cm-fg-color": "#f8f8f2",
        "--cm-active-line-bg": "rgba(255, 255, 255, 0.06)",
        "--cm-cursor-fg": "#f8f8f2",
        "--cm-line-number-fg": "#6272a4",
        "--cm-line-number-active-fg": "#f8f8f2",
        "--cm-selection-bg-inactive": "rgba(68, 71, 90, 0.6)",
        "--cm-selection-bg-focused": "rgba(68, 71, 90, 0.85)",
        "--cm-selection-highlight-bg": "rgba(68, 71, 90, 0.35)",
        "--cm-bracket-match-bg": "rgba(255, 255, 255, 0.1)",
        "--cm-bracket-match-border": "#bd93f9",
        "--cm-syntax-comment": "#6272a4",
        "--cm-syntax-keyword": "#ff79c6",
        "--cm-syntax-string": "#f1fa8c",
        "--cm-syntax-number": "#bd93f9",
        "--cm-syntax-atom": "#bd93f9",
        "--cm-syntax-property": "#66d9ef",
        "--cm-syntax-attribute": "#50fa7b",
        "--cm-syntax-variable": "#f8f8f2",
        "--cm-syntax-def": "#50fa7b",
        "--cm-syntax-bracket": "#f8f8f2",
        "--cm-syntax-tag": "#ff79c6",
        "--cm-syntax-link": "#8be9fd",
        "--cm-syntax-error": "#ff5555",
    },
    monokai: {
        "--cm-bg-color": "#272822",
        "--cm-fg-color": "#f8f8f2",
        "--cm-active-line-bg": "rgba(255, 255, 255, 0.05)",
        "--cm-cursor-fg": "#f8f8f2",
        "--cm-line-number-fg": "#75715e",
        "--cm-line-number-active-fg": "#f8f8f2",
        "--cm-selection-bg-inactive": "rgba(73, 72, 62, 0.7)",
        "--cm-selection-bg-focused": "rgba(73, 72, 62, 0.95)",
        "--cm-selection-highlight-bg": "rgba(73, 72, 62, 0.45)",
        "--cm-bracket-match-bg": "rgba(255, 255, 255, 0.1)",
        "--cm-bracket-match-border": "#a6e22e",
        "--cm-syntax-comment": "#75715e",
        "--cm-syntax-keyword": "#f92672",
        "--cm-syntax-string": "#e6db74",
        "--cm-syntax-number": "#ae81ff",
        "--cm-syntax-atom": "#ae81ff",
        "--cm-syntax-property": "#a6e22e",
        "--cm-syntax-attribute": "#a6e22e",
        "--cm-syntax-variable": "#f8f8f2",
        "--cm-syntax-def": "#a6e22e",
        "--cm-syntax-bracket": "#f8f8f2",
        "--cm-syntax-tag": "#f92672",
        "--cm-syntax-link": "#66d9ef",
        "--cm-syntax-error": "#f92672",
    },
    "one-dark": {
        "--cm-bg-color": "#282c34",
        "--cm-fg-color": "#abb2bf",
        "--cm-active-line-bg": "rgba(255, 255, 255, 0.04)",
        "--cm-cursor-fg": "#528bff",
        "--cm-line-number-fg": "#636d83",
        "--cm-line-number-active-fg": "#abb2bf",
        "--cm-selection-bg-inactive": "rgba(61, 66, 77, 0.7)",
        "--cm-selection-bg-focused": "rgba(61, 66, 77, 0.95)",
        "--cm-selection-highlight-bg": "rgba(61, 66, 77, 0.45)",
        "--cm-bracket-match-bg": "rgba(255, 255, 255, 0.08)",
        "--cm-bracket-match-border": "#528bff",
        "--cm-syntax-comment": "#5c6370",
        "--cm-syntax-keyword": "#c678dd",
        "--cm-syntax-string": "#98c379",
        "--cm-syntax-number": "#d19a66",
        "--cm-syntax-atom": "#d19a66",
        "--cm-syntax-property": "#e06c75",
        "--cm-syntax-attribute": "#d19a66",
        "--cm-syntax-variable": "#e06c75",
        "--cm-syntax-def": "#61afef",
        "--cm-syntax-bracket": "#abb2bf",
        "--cm-syntax-tag": "#e06c75",
        "--cm-syntax-link": "#61afef",
        "--cm-syntax-error": "#f44747",
    },
    "solarized-dark": {
        "--cm-bg-color": "#002b36",
        "--cm-fg-color": "#839496",
        "--cm-active-line-bg": "rgba(255, 255, 255, 0.05)",
        "--cm-cursor-fg": "#839496",
        "--cm-line-number-fg": "#586e75",
        "--cm-line-number-active-fg": "#839496",
        "--cm-selection-bg-inactive": "rgba(7, 54, 66, 0.8)",
        "--cm-selection-bg-focused": "rgba(7, 54, 66, 0.95)",
        "--cm-selection-highlight-bg": "rgba(7, 54, 66, 0.5)",
        "--cm-bracket-match-bg": "rgba(181, 137, 0, 0.25)",
        "--cm-bracket-match-border": "#b58900",
        "--cm-syntax-comment": "#586e75",
        "--cm-syntax-keyword": "#859900",
        "--cm-syntax-string": "#2aa198",
        "--cm-syntax-number": "#d33682",
        "--cm-syntax-atom": "#cb4b16",
        "--cm-syntax-property": "#268bd2",
        "--cm-syntax-attribute": "#b58900",
        "--cm-syntax-variable": "#839496",
        "--cm-syntax-def": "#268bd2",
        "--cm-syntax-bracket": "#839496",
        "--cm-syntax-tag": "#268bd2",
        "--cm-syntax-link": "#268bd2",
        "--cm-syntax-error": "#dc322f",
    },
    "material-dark": {
        "--cm-bg-color": "#263238",
        "--cm-fg-color": "#eeffff",
        "--cm-active-line-bg": "rgba(255, 255, 255, 0.05)",
        "--cm-cursor-fg": "#ffcc00",
        "--cm-line-number-fg": "#546e7a",
        "--cm-line-number-active-fg": "#eeffff",
        "--cm-selection-bg-inactive": "rgba(84, 110, 122, 0.5)",
        "--cm-selection-bg-focused": "rgba(84, 110, 122, 0.7)",
        "--cm-selection-highlight-bg": "rgba(84, 110, 122, 0.35)",
        "--cm-bracket-match-bg": "rgba(255, 255, 255, 0.1)",
        "--cm-bracket-match-border": "#80cbc4",
        "--cm-syntax-comment": "#546e7a",
        "--cm-syntax-keyword": "#c792ea",
        "--cm-syntax-string": "#c3e88d",
        "--cm-syntax-number": "#f78c6c",
        "--cm-syntax-atom": "#f78c6c",
        "--cm-syntax-property": "#82aaff",
        "--cm-syntax-attribute": "#ffcb6b",
        "--cm-syntax-variable": "#eeffff",
        "--cm-syntax-def": "#82aaff",
        "--cm-syntax-bracket": "#eeffff",
        "--cm-syntax-tag": "#f07178",
        "--cm-syntax-link": "#82aaff",
        "--cm-syntax-error": "#ff5370",
    },
};
