const CONTEXT_MENU_ICONS: Record<string, string> = {
    copyHash: 'git-commit',
    copyMessage: 'copy',
    reset: 'debug-restart',
    createBranch: 'git-branch-create',
    addTag: 'tag',
    checkout: 'arrow-swap',
    cherryPick: 'git-compare',
    revert: 'discard',
    merge: 'git-merge',
    checkoutBranch: 'arrow-swap',
    renameBranch: 'edit',
    deleteBranch: 'trash',
    mergeBranch: 'git-merge',
    pushBranch: 'repo-push',
    copyBranch: 'copy',
    checkoutRemote: 'arrow-swap',
    deleteRemoteBranch: 'trash',
    pullRemote: 'repo-pull',
    mergeRemote: 'git-merge',
    copyRemote: 'copy',
    deleteTag: 'trash',
    pushTag: 'repo-push',
    copyTag: 'copy',
    applyStash: 'git-stash-apply',
    popStash: 'git-stash-pop',
    dropStash: 'trash',
    branchFromStash: 'git-branch-create',
    pushStash: 'git-stash',
    resetUncommittedMixed: 'debug-restart-frame',
    resetUncommittedHard: 'discard',
    cleanUntracked: 'clear-all',
    viewScm: 'source-control',
    viewDiff: 'diff',
    viewFileAtRevision: 'history',
    openFile: 'go-to-file',
    copyRelPath: 'copy',
    copyAbsPath: 'copy',
    viewDiffWorking: 'diff-single',
};

export function getContextMenuIcon(id: string): string | undefined {
    return CONTEXT_MENU_ICONS[id];
}
