const CONTEXT_MENU_ICONS: Record<string, string> = {
    copyHash: 'git-commit',
    copyMessage: 'copy',
    reset: 'debug-restart',
    createBranch: 'git-branch-create',
    addTag: 'tag',
    checkout: 'arrow-swap',
    cherryPick: 'git-compare',
    revert: 'discard',
    merge: 'git-merge',
    checkoutBranch: 'arrow-swap',
    renameBranch: 'edit',
    deleteBranch: 'trash',
    mergeBranch: 'git-merge',
    pushBranch: 'repo-push',
    copyBranch: 'copy',
    checkoutRemote: 'arrow-swap',
    deleteRemoteBranch: 'trash',
    pullRemote: 'repo-pull',
    mergeRemote: 'git-merge',
    copyRemote: 'copy',
    deleteTag: 'trash',
    pushTag: 'repo-push',
    copyTag: 'copy',
    applyStash: 'git-stash-apply',
    popStash: 'git-stash-pop',
    dropStash: 'trash',
    branchFromStash: 'git-branch-create',
    pushStash: 'git-stash',
    resetUncommittedMixed: 'debug-restart-frame',
    resetUncommittedHard: 'discard',
    cleanUntracked: 'clear-all',
    viewScm: 'source-control',
    viewDiff: 'diff',
    viewFileAtRevision: 'history',
    openFile: 'go-to-file',
    copyRelPath: 'copy',
    copyAbsPath: 'copy',
    viewDiffWorking: 'diff-single',
    copySelectedHashes: 'git-commit',
    copySelectedMessages: 'copy',
    cherryPickSelected: 'git-compare',
    revertSelected: 'discard',
};

type IconColor = 'danger' | 'push' | 'pull' | 'create' | 'merge' | 'warning';

const CONTEXT_MENU_ICON_COLORS: Record<string, IconColor> = {
    deleteBranch: 'danger',
    deleteRemoteBranch: 'danger',
    deleteTag: 'danger',
    dropStash: 'danger',
    resetUncommittedHard: 'danger',
    revert: 'danger',
    revertSelected: 'danger',
    cleanUntracked: 'danger',
    pushBranch: 'push',
    pushTag: 'push',
    pushStash: 'push',
    pullRemote: 'pull',
    applyStash: 'pull',
    popStash: 'pull',
    createBranch: 'create',
    branchFromStash: 'create',
    addTag: 'create',
    merge: 'merge',
    mergeBranch: 'merge',
    mergeRemote: 'merge',
    cherryPick: 'merge',
    cherryPickSelected: 'merge',
    reset: 'warning',
    resetUncommittedMixed: 'warning',
};

export function getContextMenuIcon(id: string): string | undefined {
    return CONTEXT_MENU_ICONS[id];
}

export function getContextMenuIconColor(id: string): IconColor | undefined {
    return CONTEXT_MENU_ICON_COLORS[id];
}
